# Generated by Django 5.2 on 2025-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('ST', 'Студия'), ('1R', '1-комнатная'), ('2R', '2-комнатная'), ('3R', '3-комнатная'), ('HO', 'Дом/Коттедж'), ('OT', 'Другое')], default='1R', max_length=2, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во кроватей'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Макс. гостей'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='apartments.amenity', verbose_name='Удобства'),
        ),
    ]
