# Generated by Django 5.2 on 2025-04-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/%Y/%m/%d/', verbose_name='Фото')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apartments.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фотографии квартир',
                'ordering': ['pk'],
            },
        ),
    ]
